### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by procrastimax** [fionnfuchs/mood-tracking-diary#1]
I really appreciate this work of software my good sir.
But I sadly stumbled about the fact, that this codebase does not provide any tests.
This makes it really hard for an ambitious coder like me (last commit probably from 2019) to implement more useful functions like how many "Sternis" I drank on a day I felt good.

I would treasure if you could implement some tests.

(also no issue template)

**Comment by fionnfuchs** [comment]
Test driven development is a **scam** by corporate developers to increase their leisure time at work. It clearly does not provide any benefit. It is thereby deemed as a **cringe practice** and **not based**.
